### ISSUE TITLE
How's the performance？

### ISSUE THREAD

**Issue by jensenzhoujh** [arbitularov/SiamRPN-PyTorch#2]
How‘s the tracking result  using GOT-10k as training set compared with the large volume of YouTube-BB?

**Comment by arbitularov** [comment]
I have not finished the test section yet. When I finished, I will let you know (:

**Comment by arbitularov** [comment]
不要着急朋友，我还没写完代码。完了以后我告诉你，好吗？

**Comment by wangaixue** [comment]
your works  is really  good. such as siamfc and this
